SOURCES= \
 "CvArea.cpp" \
 "CvArtFileMgr.cpp" \
 "CvBugOptions.cpp" \
 "CvCity.cpp" \
 "CvCityAI.cpp" \
 "CvDeal.cpp" \
 "CvDiploParameters.cpp" \
 "CvDLLButtonPopup.cpp" \
 "CvDLLEntity.cpp" \
 "CvDLLPython.cpp" \
 "CvDllPythonEvents.cpp" \
 "CvDllTranslator.cpp" \
 "CvDLLWidgetData.cpp" \
 "CvEventReporter.cpp" \
 "CvFractal.cpp" \
 "CvGame.cpp" \
 "CvGameAI.cpp" \
 "CvGameCoreDLL.cpp" \
 "CvGameCoreUtils.cpp" \
 "CvGameInterface.cpp" \
 "CvGameTextMgr.cpp" \
 "CvGlobals.cpp" \
 "CvHallOfFameInfo.cpp" \
 "CvInfos.cpp" \
 "CvInfoWater.cpp" \
 "CvInitCore.cpp" \
 "CvMap.cpp" \
 "CvMapGenerator.cpp" \
 "CvMessageControl.cpp" \
 "CvMessageData.cpp" \
 "CvPlayer.cpp" \
 "CvPlayerAI.cpp" \
 "CvPlot.cpp" \
 "CvPlotGroup.cpp" \
 "CvPopupInfo.cpp" \
 "CvPopupReturn.cpp" \
 "CvRandom.cpp" \
 "CvReplayInfo.cpp" \
 "CvReplayMessage.cpp" \
 "CvSelectionGroup.cpp" \
 "CvSelectionGroupAI.cpp" \
 "CvStatistics.cpp" \
 "CvStructs.cpp" \
 "CvTalkingHeadMessage.cpp" \
 "CvTeam.cpp" \
 "CvTeamAI.cpp" \
 "CvTextScreens.cpp" \
 "CvUnit.cpp" \
 "CvUnitAI.cpp" \
 "CvXMLLoadUtility.cpp" \
 "CvXMLLoadUtilityGet.cpp" \
 "CvXMLLoadUtilityInit.cpp" \
 "CvXMLLoadUtilitySet.cpp" \
 "CyArea.cpp" \
 "CyAreaInterface.cpp" \
 "CyArgsList.cpp" \
 "CyArtFileMgr.cpp" \
 "CyArtFileMgrInterface.cpp" \
 "CyCity.cpp" \
 "CyCityInterface1.cpp" \
 "CyDeal.cpp" \
 "CyEnumsInterface.cpp" \
 "CyGame.cpp" \
 "CyGameCoreUtils.cpp" \
 "CyGameCoreUtilsInterface.cpp" \
 "CyGameInterface.cpp" \
 "CyGameTextMgr.cpp" \
 "CyGameTextMgrInterface.cpp" \
 "CyGlobalContext.cpp" \
 "CyGlobalContextInterface1.cpp" \
 "CyGlobalContextInterface2.cpp" \
 "CyGlobalContextInterface3.cpp" \
 "CyGlobalContextInterface4.cpp" \
 "CyHallOfFameInfo.cpp" \
 "CyHallOfFameInterface.cpp" \
 "CyInfoInterface1.cpp" \
 "CyInfoInterface2.cpp" \
 "CyInfoInterface3.cpp" \
 "CyMap.cpp" \
 "CyMapGenerator.cpp" \
 "CyMapGeneratorInterface.cpp" \
 "CyMapInterface.cpp" \
 "CyMessageControl.cpp" \
 "CyMessageControlInterface.cpp" \
 "CyPlayer.cpp" \
 "CyPlayerInterface1.cpp" \
 "CyPlayerInterface2.cpp" \
 "CyPlot.cpp" \
 "CyPlotInterface1.cpp" \
 "CyRandomInterface.cpp" \
 "CyReplayInfo.cpp" \
 "CySelectionGroup.cpp" \
 "CySelectionGroupInterface.cpp" \
 "CyStructsInterface1.cpp" \
 "CyTeam.cpp" \
 "CyTeamInterface.cpp" \
 "CyUnit.cpp" \
 "CyUnitInterface1.cpp" \
 "FAssert.cpp" \
 "FDialogTemplate.cpp" \
 "_precompile.cpp" \

Debug_OBJS= \
 Debug\CvArea.obj \
 Debug\CvArtFileMgr.obj \
 Debug\CvBugOptions.obj \
 Debug\CvCity.obj \
 Debug\CvCityAI.obj \
 Debug\CvDeal.obj \
 Debug\CvDiploParameters.obj \
 Debug\CvDLLButtonPopup.obj \
 Debug\CvDLLEntity.obj \
 Debug\CvDLLPython.obj \
 Debug\CvDllPythonEvents.obj \
 Debug\CvDllTranslator.obj \
 Debug\CvDLLWidgetData.obj \
 Debug\CvEventReporter.obj \
 Debug\CvFractal.obj \
 Debug\CvGame.obj \
 Debug\CvGameAI.obj \
 Debug\CvGameCoreDLL.obj \
 Debug\CvGameCoreUtils.obj \
 Debug\CvGameInterface.obj \
 Debug\CvGameTextMgr.obj \
 Debug\CvGlobals.obj \
 Debug\CvHallOfFameInfo.obj \
 Debug\CvInfos.obj \
 Debug\CvInfoWater.obj \
 Debug\CvInitCore.obj \
 Debug\CvMap.obj \
 Debug\CvMapGenerator.obj \
 Debug\CvMessageControl.obj \
 Debug\CvMessageData.obj \
 Debug\CvPlayer.obj \
 Debug\CvPlayerAI.obj \
 Debug\CvPlot.obj \
 Debug\CvPlotGroup.obj \
 Debug\CvPopupInfo.obj \
 Debug\CvPopupReturn.obj \
 Debug\CvRandom.obj \
 Debug\CvReplayInfo.obj \
 Debug\CvReplayMessage.obj \
 Debug\CvSelectionGroup.obj \
 Debug\CvSelectionGroupAI.obj \
 Debug\CvStatistics.obj \
 Debug\CvStructs.obj \
 Debug\CvTalkingHeadMessage.obj \
 Debug\CvTeam.obj \
 Debug\CvTeamAI.obj \
 Debug\CvTextScreens.obj \
 Debug\CvUnit.obj \
 Debug\CvUnitAI.obj \
 Debug\CvXMLLoadUtility.obj \
 Debug\CvXMLLoadUtilityGet.obj \
 Debug\CvXMLLoadUtilityInit.obj \
 Debug\CvXMLLoadUtilitySet.obj \
 Debug\CyArea.obj \
 Debug\CyAreaInterface.obj \
 Debug\CyArgsList.obj \
 Debug\CyArtFileMgr.obj \
 Debug\CyArtFileMgrInterface.obj \
 Debug\CyCity.obj \
 Debug\CyCityInterface1.obj \
 Debug\CyDeal.obj \
 Debug\CyEnumsInterface.obj \
 Debug\CyGame.obj \
 Debug\CyGameCoreUtils.obj \
 Debug\CyGameCoreUtilsInterface.obj \
 Debug\CyGameInterface.obj \
 Debug\CyGameTextMgr.obj \
 Debug\CyGameTextMgrInterface.obj \
 Debug\CyGlobalContext.obj \
 Debug\CyGlobalContextInterface1.obj \
 Debug\CyGlobalContextInterface2.obj \
 Debug\CyGlobalContextInterface3.obj \
 Debug\CyGlobalContextInterface4.obj \
 Debug\CyHallOfFameInfo.obj \
 Debug\CyHallOfFameInterface.obj \
 Debug\CyInfoInterface1.obj \
 Debug\CyInfoInterface2.obj \
 Debug\CyInfoInterface3.obj \
 Debug\CyMap.obj \
 Debug\CyMapGenerator.obj \
 Debug\CyMapGeneratorInterface.obj \
 Debug\CyMapInterface.obj \
 Debug\CyMessageControl.obj \
 Debug\CyMessageControlInterface.obj \
 Debug\CyPlayer.obj \
 Debug\CyPlayerInterface1.obj \
 Debug\CyPlayerInterface2.obj \
 Debug\CyPlot.obj \
 Debug\CyPlotInterface1.obj \
 Debug\CyRandomInterface.obj \
 Debug\CyReplayInfo.obj \
 Debug\CySelectionGroup.obj \
 Debug\CySelectionGroupInterface.obj \
 Debug\CyStructsInterface1.obj \
 Debug\CyTeam.obj \
 Debug\CyTeamInterface.obj \
 Debug\CyUnit.obj \
 Debug\CyUnitInterface1.obj \
 Debug\FAssert.obj \
 Debug\FDialogTemplate.obj \
 Debug\_precompile.obj \

Release_OBJS= \
 Release\CvArea.obj \
 Release\CvArtFileMgr.obj \
 Release\CvBugOptions.obj \
 Release\CvCity.obj \
 Release\CvCityAI.obj \
 Release\CvDeal.obj \
 Release\CvDiploParameters.obj \
 Release\CvDLLButtonPopup.obj \
 Release\CvDLLEntity.obj \
 Release\CvDLLPython.obj \
 Release\CvDllPythonEvents.obj \
 Release\CvDllTranslator.obj \
 Release\CvDLLWidgetData.obj \
 Release\CvEventReporter.obj \
 Release\CvFractal.obj \
 Release\CvGame.obj \
 Release\CvGameAI.obj \
 Release\CvGameCoreDLL.obj \
 Release\CvGameCoreUtils.obj \
 Release\CvGameInterface.obj \
 Release\CvGameTextMgr.obj \
 Release\CvGlobals.obj \
 Release\CvHallOfFameInfo.obj \
 Release\CvInfos.obj \
 Release\CvInfoWater.obj \
 Release\CvInitCore.obj \
 Release\CvMap.obj \
 Release\CvMapGenerator.obj \
 Release\CvMessageControl.obj \
 Release\CvMessageData.obj \
 Release\CvPlayer.obj \
 Release\CvPlayerAI.obj \
 Release\CvPlot.obj \
 Release\CvPlotGroup.obj \
 Release\CvPopupInfo.obj \
 Release\CvPopupReturn.obj \
 Release\CvRandom.obj \
 Release\CvReplayInfo.obj \
 Release\CvReplayMessage.obj \
 Release\CvSelectionGroup.obj \
 Release\CvSelectionGroupAI.obj \
 Release\CvStatistics.obj \
 Release\CvStructs.obj \
 Release\CvTalkingHeadMessage.obj \
 Release\CvTeam.obj \
 Release\CvTeamAI.obj \
 Release\CvTextScreens.obj \
 Release\CvUnit.obj \
 Release\CvUnitAI.obj \
 Release\CvXMLLoadUtility.obj \
 Release\CvXMLLoadUtilityGet.obj \
 Release\CvXMLLoadUtilityInit.obj \
 Release\CvXMLLoadUtilitySet.obj \
 Release\CyArea.obj \
 Release\CyAreaInterface.obj \
 Release\CyArgsList.obj \
 Release\CyArtFileMgr.obj \
 Release\CyArtFileMgrInterface.obj \
 Release\CyCity.obj \
 Release\CyCityInterface1.obj \
 Release\CyDeal.obj \
 Release\CyEnumsInterface.obj \
 Release\CyGame.obj \
 Release\CyGameCoreUtils.obj \
 Release\CyGameCoreUtilsInterface.obj \
 Release\CyGameInterface.obj \
 Release\CyGameTextMgr.obj \
 Release\CyGameTextMgrInterface.obj \
 Release\CyGlobalContext.obj \
 Release\CyGlobalContextInterface1.obj \
 Release\CyGlobalContextInterface2.obj \
 Release\CyGlobalContextInterface3.obj \
 Release\CyGlobalContextInterface4.obj \
 Release\CyHallOfFameInfo.obj \
 Release\CyHallOfFameInterface.obj \
 Release\CyInfoInterface1.obj \
 Release\CyInfoInterface2.obj \
 Release\CyInfoInterface3.obj \
 Release\CyMap.obj \
 Release\CyMapGenerator.obj \
 Release\CyMapGeneratorInterface.obj \
 Release\CyMapInterface.obj \
 Release\CyMessageControl.obj \
 Release\CyMessageControlInterface.obj \
 Release\CyPlayer.obj \
 Release\CyPlayerInterface1.obj \
 Release\CyPlayerInterface2.obj \
 Release\CyPlot.obj \
 Release\CyPlotInterface1.obj \
 Release\CyRandomInterface.obj \
 Release\CyReplayInfo.obj \
 Release\CySelectionGroup.obj \
 Release\CySelectionGroupInterface.obj \
 Release\CyStructsInterface1.obj \
 Release\CyTeam.obj \
 Release\CyTeamInterface.obj \
 Release\CyUnit.obj \
 Release\CyUnitInterface1.obj \
 Release\FAssert.obj \
 Release\FDialogTemplate.obj \
 Release\_precompile.obj \

